name: CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  NSERVICEBUS_AMAZONSQS_S3BUCKET: ${{ secrets.NSERVICEBUS_AMAZONSQS_S3BUCKET }}
jobs:
  build:
    name: ${{ matrix.os.name }}-${{ matrix.framework }}
    runs-on: ${{ matrix.os.platform }}
    strategy:
      matrix:
        os:
          - { platform: windows-2019, name: Windows }
          - { platform: ubuntu-20.04, name: Linux }
        framework: [ net472, net6.0 ]
        exclude:
          - os: { name: Linux }
            framework: net472
      fail-fast: false
    steps:
      - name: Check for secrets
        env:
          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
        shell: pwsh
        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build src --configuration Release
      - name: Upload packages
        if: matrix.name == 'Windows' && matrix.framework == 'net6.0'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: NuGet packages
          path: nugets/
          retention-days: 7
      - name: Set fixed test prefix (2)
        shell: pwsh
        run: |
          $os = '${{ matrix.os.name }}'
          $framework = '${{ matrix.framework }}'
          # Value like 'Fixed-Win-net6-0'
          echo "NServiceBus_AmazonSQS_AT_CustomFixedNamePrefix=Fixed_$($os.substring(0,3))_$($framework.replace('.','_'))" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Run tests
        uses: Particular/run-tests-action@v1.3.0
        with:
          framework: ${{ matrix.framework }}
